# Generated by Django 4.2.10 on 2024-02-24 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("resources", models.JSONField(blank=True)),
                (
                    "profit",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Not Scheduled Yet"), (1, "Scheduled")], default=0
                    ),
                ),
            ],
            options={
                "ordering": ["-profit"],
            },
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                check=models.Q(("profit__gte", 0)), name="profit_gte_0"
            ),
        ),
    ]
